### ISSUE TITLE
SVG Styles

### ISSUE THREAD

**Issue by DenisCarriere** [KrateLabs/KrateLabs-App#5]
- [ ] Produce multiple SVG (Water, Roads, Full)
- [ ] Update Product Description with those images

All SVG's will be added to the Product description, that way if a User decides to do a purchase on a specific item, all the available SVG files will apart of that description. They are hosted on Amazon S3 bucket.

![image](https://cloud.githubusercontent.com/assets/550895/16536827/95ebc3fa-3fc5-11e6-8eb7-ab873ca33db8.png)
 

-----------------------

**Question**

Also am I going to be sent a direct SVG with the black and white options like we discussed also?

Where did we net out with the decreasing line width. The more files that I can get sent directly the better, that way I can manage and edit the unique fields appropriately. 

Most of them were already outlined in the below To Do task list below. 

----------------------

**Question**

Also wondering if it’s possible to decrease the width of the lines for the roads. Our lasering time has increased by 20% and I’m hoping that we’re able to start with a smaller line weight initially so tha

Basically this is my process from the SVG files you submit: 
1. Take all white waterline (with black water) > invert colours > increase stroke (output below)

![screen shot 2016-05-25 at 5 03 47 pm](https://cloud.githubusercontent.com/assets/17345560/15556205/c2768df8-229a-11e6-95db-7a824a9f979c.png)

2. Take roads only (which is a trace) and increase / decease line weight to fill in the stroke gaps 

![screen shot 2016-05-25 at 5 02 48 pm](https://cloud.githubusercontent.com/assets/17345560/15556238/f2936f24-229a-11e6-9549-6309907d922c.png)

3. Roads come as trace, therefore the smaller the original file, the better 
4. Then merge the two files 

![screen shot 2016-05-25 at 5 04 00 pm](https://cloud.githubusercontent.com/assets/17345560/15556248/fec6a1c6-229a-11e6-8617-7d92f6eb4897.png)

Make adjustments and match the line weights so it's all consistent. 

Is is possible to decrease the output line stoke / weight so that I can minimally increase stroke. It would be ideal to have it extremely thin just from the backend, because what the customer see's from the web app component works well.

**Comment by DenisCarriere** [comment]
@BradonL Slight issues rendering thin road lines.

I'm using Potrace right now, I don't know any softwares available that can be ran in the Command Line that does a good job.

http://potrace.sourceforge.net/

![image](https://cloud.githubusercontent.com/assets/550895/16538175/7b28f7b2-3fe9-11e6-8227-dfd5016d676c.png)

https://s3.amazonaws.com/api.kratelabs.com/products/57773cb7677fa0233cac7f89/57773cb7677fa0233cac7f89-roads.svg

**Comment by BradonL** [comment]
Hey Denis, 

That’s ok not to worry. I’m sure down the road I’ll be able to figure out something from the Adobe end, that works on my end! 

I also tried to edit the copy on the GitHub page. I don’t see the changes right away, but perhaps it takes a bit to pop up. It asked me  to “add to branch master” or as a “pull request” so I just clicked the default, which was “branch master.” 

Please let me know.

Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
@BradonL Hey Bradon, you did it correctly, however I did not set it up to restart automatically at every commit. If something breaks during one of those new commits then your service is down and I might not be available immediately to fix it.

I could add some tests that run after the new commits and if the tests pass then it will restart the server.

I've restarted the server manually, so you should see the changes now.

Cheers,

**Comment by DenisCarriere** [comment]
@BradonL Got the auto-restart working and tested... Just make sure you pay attention what you edit when committing to **master** branch since it will restart at every commit.

Cheers,

https://github.com/KrateLabs/KrateLabs-REST/commit/a6189560521caab11b10fcf71f91176f8a21cdb2

**Comment by BradonL** [comment]
Ok will do. I’m assuming if I made an changes and there was an error, I would see that right away on the site correct? 

I was making some rendering for the website today, and the one thing I noticed would be the “Water” paths for ferries or boats that are still in the style. Wondering if you’d be able to remove those? Spent all day yesterday finalizing all of the renderings on the website and getting that component dialled in. These things take time, haha. Rewarding overall though. 

Hope you’re having a nice weekend. 

Thanks,
Bradon.








Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
I've removed the **ferries** from the `Road` & `Full` Mapbox styles, you shouldn't see them anymore.

As for the auto-changes, you should see the changes appear within 10-30 seconds after pushing a new commit. If there's an error like breaking the code, unfortunately the service will stop working. I'd have to add some tests to make sure each commit is valid before restarting the service. I can add that soon, but don't be afraid to break it, just make sure if you do changes confirm afterwards that it is still working.

Area with a ferry:
https://kratelabs.com/#/14.7/45.5225/-75.4135/0/0/app?material=2&orientation=2&search=&size=3&style=1&_k=yqhm4c

**Comment by DenisCarriere** [comment]
@BradonL I added a small testing suite to make sure the API doesn't break when we push a bad commit.

Any errors that occur during the tests will not update the live API.

You'll see a TravisCI badge with "passing/error" [![Build Status](https://travis-ci.org/KrateLabs/KrateLabs-REST.svg?branch=master)](https://travis-ci.org/KrateLabs/KrateLabs-REST)

You can see the test logs here:

https://travis-ci.org/KrateLabs/KrateLabs-REST

**Comment by BradonL** [comment]
Hey Denis, 

Thats perfect thanks. I was using it on the weekend and just now and every couple of times I enter a location and “add to cart” nothing happens.  The loading wheel  shows up like it’s doing something but nothing actually happens. Any idea what this could be? 

I was just trying to finishing some renderings. Please let me know. 

I’m doing a couple maps for a wedding coming up also, take a look at the below rendering. Going to start affiliate marketing with some wedding planners for some maps. Big big industry! 

Thanks,
Bradon.



Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
I'll look into this and get back to you. It might be because the server is
tiny (1 core, 500MB RAM). Maybe once there's many requests it stops... :(
oh computers...

It will take me some time to figure out what to do on this one.

**Comment by DenisCarriere** [comment]
@BradonL Oh in this case it was down because the service was broken (My fault, I added a new package dependency and the "autostart" didn't include a step to install new dependencies). It should be working again now.
If you want to test if the background API is working, go to the root of the API.

https://api.kratelabs.addxy.com/

You'll see this:

```json
{
  "api": "Kratelabs",
  "ok": true,
  "status": 200,
  "message": "Demonstrates the Kratelabs API, yay!!",
  "http": [
    {
      "url": "/product",
      "method": "GET"
    },
    {
      "url": "/token",
      "method": "GET"
    },
    {
      "url": "/user",
      "method": "GET"
    }
  ]
}
```

**Comment by DenisCarriere** [comment]
@BradonL I've added something that will detect if there's any internal server errors, ideally this should never show up, but if there is something wrong, it will immediately stop the spinner and show you that there was an error.

![image](https://cloud.githubusercontent.com/assets/550895/16839638/26562bd8-499e-11e6-8ced-87f253d873e3.png)

**Comment by BradonL** [comment]
Hey Denis,

That’s exactly what I was looking for thanks so much! Everything works fine now.

Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by BradonL** [comment]
Hey Denis, 

The ferry items are still showing up for some reason. When I also tried the Toronto map the Toronto Island didn’t show up in the SVG files. 

Please let me know. 

Thanks,
Bradon.




Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
@BradonL I updated the `Road SVG`, that was the only one that still had Ferries.

I've updated the back-end to create new SVG without ferries now, and if you are still seeing ferries inside your app, you might have to clear your browser cache.

Example:
https://kratelabs.com/products/579044c9ce2341ca728cf9d2

![image](https://cloud.githubusercontent.com/assets/550895/17010698/4938b25c-4ed4-11e6-8ba8-f364aa7ef1d2.png)

**Comment by BradonL** [comment]
Hey Denis, 

This error keeps coming up. I need to get some creative files done for the AM. 

Please let me know! 

Hope you’re well, saw you recently got a new job?? Very exciting. 

Thanks,
Bradon. 




Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
It's strange, the API is up and running but I'm also getting an internal
error.

I'll look into this tonight and try to fix this.

**Comment by BradonL** [comment]
Hey Denis, 

Thanks for the quick response, appreciate it. 

Thanks,
Bradon. 

416.558.0773
Bradon Levalds
blevalds@gmail.com

**Comment by DenisCarriere** [comment]
@BradonL Everything should be running back to normal, conflicting Amazon S3 credentials on the server.
